instagram_celebrities = [
    {"name": "Khloe Kardashian", "follower_count": 269.3, "occupation": "Model & Socialite", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 256.4, "occupation": "Musician", "country": "Canada"},
    {"name": "Kendall Jenner", "follower_count": 255.7, "occupation": "Model", "country": "United States"},
    {"name": "National Geographic", "follower_count": 238.2, "occupation": "Media Channel", "country": "United States"},
    {"name": "Nike", "follower_count": 236, "occupation": "Sports Brand", "country": "United States"},
    {"name": "Taylor Swift", "follower_count": 223.5, "occupation": "Musician", "country": "United States"},
    {"name": "Lionel Messi", "follower_count": 464, "occupation": "Footballer", "country": "Argentina"},
    {"name": "Kylie Jenner", "follower_count": 399, "occupation": "Businesswoman & Model", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 366, "occupation": "Television Personality & Businesswoman", "country": "United States"},
    {"name": "Beyoncé", "follower_count": 311, "occupation": "Musician", "country": "United States"},
    {"name": "Virat Kohli", "follower_count": 264.4, "occupation": "Cricketer", "country": "India"},
    {"name": "Neymar", "follower_count": 216.8, "occupation": "Footballer", "country": "Brazil"},
    {"name": "Nicki Minaj", "follower_count": 228.3, "occupation": "Musician", "country": "United States"},
    {"name": "Miley Cyrus", "follower_count": 215.7, "occupation": "Musician", "country": "United States"},
    {"name": "Rihanna", "follower_count": 152.7, "occupation": "Musician & Businesswoman", "country": "Barbados"},
    {"name": "Deepika Padukone", "follower_count": 80.3, "occupation": "Actress", "country": "India"},
    {"name": "Hailey Bieber", "follower_count": 53.5, "occupation": "Model", "country": "United States"},
    {"name": "Vinicius Jr.", "follower_count": 50, "occupation": "Footballer", "country": "Brazil"},
    {"name": "Travis Scott", "follower_count": 58.1, "occupation": "Musician", "country": "United States"},
    {"name": "Alia Bhatt", "follower_count": 85.4, "occupation": "Actress", "country": "India"},
    {"name": "Anushka Sharma", "follower_count": 68.6, "occupation": "Actress", "country": "India"},
    {"name": "Olivia Rodrigo", "follower_count": 37.9, "occupation": "Musician & Actress", "country": "United States"},
    {"name": "Priyanka Chopra", "follower_count": 92, "occupation": "Actress", "country": "India"},
    {"name": "Jennifer Lopez", "follower_count": 251, "occupation": "Musician & Actress", "country": "United States"},
    {"name": "Cristiano Ronaldo", "follower_count": 624, "occupation": "Footballer", "country": "Portugal"},
    {"name": "Selena Gomez", "follower_count": 430, "occupation": "Musician & Actress", "country": "United States"},
    {"name": "Ariana Grande", "follower_count": 380, "occupation": "Musician", "country": "United States"},
    {"name": "Kourtney Kardashian", "follower_count": 224.8, "occupation": "Reality TV Star & Businesswoman", "country": "United States"},
    {"name": "IShowSpeed", "follower_count": 25.4, "occupation": "Streamer", "country": "United States"},
    {"name": "Narendra Modi", "follower_count": 91.7, "occupation": "Prime Minister", "country": "India"},
    {"name": "Georgina Rodriguez", "follower_count": 63.7, "occupation": "Model", "country": "Spain"}
]


